### PR TITLE
add tooltip prototype

### LINKED ISSUE #22: Add tooltips for vote options
add tooltips for the ✂🤷‍♀️🍵 buttons

### PR DESCRIPTION
**Pull request by eum2o**
Example for #22 for further discussion.

### CODE REVIEW

**Comment by eum2o** [comment]
This is how a tooltip currently looks (default of the [react-tooltip](https://www.npmjs.com/package/react-tooltip) component):

image
image

Seeking feedback from @SVNKoch and @ingomohr:
* Should tooltips be displayed for standard numbers (0, 1, 2, etc.)?
* Any suggestions for improved tooltip texts?
  * Check all texts here: https://github.com/eum2o/planning-poker/blob/tooltips/src/cards.js
* Anything else?

**Comment by ingomohr** [comment]
Looks great, @eum2o ! 😍

I would expect tooltips only on the non-int cards because whether some int card requires low effort or not is imho up to the team and the work they estimate. The only common thing is that the estimation correlates w/ the numbers - so the tooltips on those int cards might be misleading. e.g. what card would mach: "It should be rather low effort, but the task has a high risk"...

On the others I would like:
🤷‍♂️ "Don't know" or "Can't tell"
☕️ "Need a break"
✂️ "Too big for one ticket"

**Comment by ingomohr** [comment]
Looks good 2 me now. ^^

**Comment by eum2o** [comment]
Thank you for the feedback @ingomohr. I appreciate it. I agree with your suggestion to avoid displaying tooltips for the numbers to prevent anchoring their meaning. I have also made updates to the tooltips for the three special cards as you suggested. I made a slight modification to the tooltip for "✂️" because I wanted to include "cut"

image

**Comment by eum2o** [comment]
I have made another update to it. I'm unable to decide (comments regarding this are welcome, but if you're no longer interested, I will sleep on it and make a decision later).

* Too large, needs to be cut
* Too big, needs cutting
* Too big for one ticket

**Comment by ingomohr** [comment]
How about
- "Cut into estimatable parts" or 
- "Cut into manageable parts"
?

**Comment by ingomohr** [comment]
Or "Too big to estimate"?

**Comment by ingomohr** [comment]
"Too big to handle"?

**Comment by eum2o** [comment]
Cut smaller

**Comment by ingomohr** [comment]
> Cut smaller

Mmmmeh-ish. Sounds kinda denglish to me. 😉

**Comment by eum2o** [comment]
As discussed with @ingomohr our favorite tooltip for the ✂️ is:

"Cut into smaller parts"

**Pull request merged**
