### PR TITLE
link github repo

### LINKED ISSUE #25: Add Link to Github Repo
Add a link to this GitHub repo in the UI. For example in the footer or whatever looks good.

Motivation: Users using this app can quickly jump to this repo to create issues or to contribute.

### PR DESCRIPTION
**Pull request by sohaibaumer**
Fixes #25 

Wasn't making any sense elsewhere like in the footer, feel free to tweek around.

image

### CODE REVIEW

**Comment by eum2o** [comment]
Thank you for your contribution! I appreciate it. The visual aspect of the solution looks good to me, and I can't think of a better place for the GitHub link.

However, I have some concerns about the implementation. The use of an SVG graphic seems a bit suboptimal to me because SVG data can be hard to read and maintain. I'm wondering if it might be better to use a React library for the GitHub logo. This way, we can ensure consistency with how the logo appears on other pages, and it could potentially provide more maintainability in the long run.

**Comment by sohaibaumer** [comment]
Yeah, I did check for any pre-existing icon packages in your project but didn't find any, so it didn't seem like a good idea ATT to add a new package for just a single icon. React-icons package would serve the purpose, I'll add that and update shortly.

**Comment by eum2o** [comment]
Cool, thank you. Adding a new package is totally fine.

**Comment by sohaibaumer** [comment]
Its done.

image

**Comment by eum2o** [comment]
It's great. I locally tested it and the link works fine. Again, thank you for you contribution, ser

**Pull request merged**
