### PR TITLE
fix: preserve session data beyond browser-refresh

### LINKED ISSUE #1: Browser-Refresh Moves the User Back to User-Registration Page
We should fix this so that a browser-refresh just refreshes the content that is displayed according to the model status.

### PR DESCRIPTION
**Pull request by ingomohr**
## Change
`userName` and `userNameSubmitted` are now written to and read from the `sessionStorage`. This prevents that session data from being wiped out whenever the browser gets refreshed.

* I didn't add the `users` list to it because that is stored on the server right now.

### CODE REVIEW

**Comment by ingomohr** [comment]
Sorry for dem further forces. There was an unwanted change (1st try), then there was an unwanted file lul (2nd try).

#gitMixedResetForDemWin ;)

**Review by eum2o — CHANGES_REQUESTED** [review]
Thanks for contributing, @ingomohr! The changes you made look good overall. However, there is an issue where the user can undo their card selection by refreshing the page, which shouldn't be possible. To fix this, you'll need to synchronize the estimation state with the `sessionStorage`, as this state affects the enablement of card buttons

See `App.js` line 122:
```
disabled={estimation !== null}
```

Sorry for not having tests, yet 😇

**Comment by ingomohr** [comment]
Gotcha. Will do. Missed that one. 😊

**Comment by ingomohr** [comment]
## Change
Added estimation to sessionStorage, too.

Manual integration test:
estimation-preserved

**Comment by eum2o** [comment]
Great job, @ingomohr! Your updated pull request and the GIF are much appreciated. It looks like the issue #1 has been resolved now.

**Review by eum2o — APPROVED** [review]

**Pull request merged**
